### ISSUE TITLE
Bug when using Prettier module

### ISSUE THREAD

**Issue by EranNL** [Futurice-project/Friendship-App#2]
Before a commit is made, module Prettier runs. But, there is a bug in the module, also stated in the issues of the github project of Prettier (https://github.com/prettier/prettier/issues/662) which adds a comma in front of closing brackets causing an error.

Example: 
```JAVASCRIPT
if (answers.options.includes('view')) {
      actions = actions.concat(
        createView('generators/templates/ComponentContainerView.js.hbs'), <--
      );
```

Possible temporary solution is to use the `--no-verify` flag when committing, until the bug is fixed. And because prettier wont verify your codes then: check them by yourself!

**Comment by jyrienstra** [comment]
Updating Node JS to the latest version will fix this issue.
